$env:AUTO_STONKS_MASTER_KEY='PKCIVFDHCOF37CXLQ3DTYTPTQ2'
$env:NEW_ALPACA_API_KEY='PKN4WKUMJ3H2M3TCEIEMQFYJCR'
$env:NEW_ALPACA_API_SECRET='3Y9uAZEe9iRn32KnUnL86CjtXfjoKFD2eSVQnCef66hz'
cd backend
cargo run --bin fix_creds
